# Generated by Django 5.0.14 on 2026-01-13 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeTen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math', models.PositiveIntegerField(blank=True, null=True)),
                ('physics', models.PositiveIntegerField(blank=True, null=True)),
                ('chemistry', models.PositiveIntegerField(blank=True, null=True)),
                ('biology', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=60)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math', models.PositiveIntegerField(blank=True, null=True)),
                ('physics', models.PositiveIntegerField(blank=True, null=True)),
                ('chemistry', models.PositiveIntegerField(blank=True, null=True)),
                ('biology', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=60)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
